Optimize the functions of fork management, mortgage redemption and fork repair
BigBang-Foundation/BigBang pull request #33
Opened 2020-11-12 03:21 UTC by cchanm

2020-11-12 06:44 UTC, StoneJobs commented on src/bigbang/blockchain.cpp
> +#include "../common/template/fork.h"
#include "template/fork.h"

2020-11-16 02:57 UTC, AlexiaChen approved these changes

2020-11-16 02:57 UTC, AlexiaChen commented on src/common/forkcontext.h
> +class CForkContext
这个类不用继承关系描述了吗？不然怎么兼容老数据

2020-11-16 02:57 UTC, AlexiaChen commented on src/storage/forkdb.cpp
> +}
这个函数实为了干啥，要特别写个Write

2020-11-16 03:04 UTC, StoneJobs requested changes

2020-11-16 03:04 UTC, StoneJobs commented on src/bigbang/blockchain.cpp
> +            }
没内存了才会触发，不必写这种防御代码

2020-11-16 03:04 UTC, StoneJobs commented on src/bigbang/blockchain.cpp
> +        if (tx.nType != CTransaction::TX_DEFI_REWARD)
原代码有“!pTxPool->Exists(txid)”，这里去掉了，原因是什么？

2020-11-16 03:04 UTC, StoneJobs commented on test/defi_test.cpp
> +    profile.defi.mapPromotionTokenTimes.insert(std::make_pair(10000, 10));                                               // �����ƹ����棬С�ڵ���10000�Ĳ��֣�Ҫ�Ŵ�10��
乱码

2020-11-16 03:04 UTC, StoneJobs commented on test/defi_test.cpp
> +    profile.defi.mapPromotionTokenTimes.insert(std::make_pair(10000, 10));                                               // �����ƹ����棬С�ڵ���10000�Ĳ��֣�Ҫ�Ŵ�10��
下面还有乱码，需要一并解决

2020-11-16 03:05 UTC, StoneJobs commented on src/bigbang/blockchain.cpp
> +        if (tx.nType != CTransaction::TX_DEFI_REWARD)
如果没有特殊原因，会降低验证效率的

2020-11-16 03:08 UTC, StoneJobs commented
应当禁止fork模板地址转给自己，以防利用高额交易费、联合某个dpos节点，提前变相赎回押金

2020-11-16 03:21 UTC, cchanm commented on src/common/forkcontext.h
> +class CForkContext
可以兼容老数据，序列化代码具有兼容老数据的功能，并且在checkrepair里有修复老数据的功能，这个已使用老数据测试了

2020-11-16 03:22 UTC, cchanm commented on src/storage/forkdb.cpp
> +}
用于CForkDB里获得hashGenesisBlock的值，并用于获得有效FORKID

2020-11-16 03:23 UTC, cchanm commented on src/bigbang/blockchain.cpp
> +        if (tx.nType != CTransaction::TX_DEFI_REWARD)
进入交易池的交易，随着高度增加，并非是有效的交易，所以这里也需要较验

2020-11-16 03:24 UTC, cchanm commented on test/defi_test.cpp
> +    profile.defi.mapPromotionTokenTimes.insert(std::make_pair(10000, 10));                                               // �����ƹ����棬С�ڵ���10000�Ĳ��֣�Ҫ�Ŵ�10��
这个乱码可能是merge的时候产生的，我改一下

2020-11-16 07:26 UTC, StoneJobs commented on src/bigbang/blockchain.cpp
> +        if (tx.nType != CTransaction::TX_DEFI_REWARD)
无效的交易应该按dex模板那种模式及时删除，否则txpool原有的特性就丢弃了：可以不需要重复验证。希望你能好好考虑原有特性，不要随意删除，原设计都是有逻辑的

2020-11-17 02:37 UTC, merged