Reduce secure memory
BigBang-Foundation/BigBang pull request #34
Opened 2020-11-12 09:07 UTC by AlexiaChen

issue #19

2020-11-13 09:21 UTC, StoneJobs requested changes

2020-11-13 09:21 UTC, StoneJobs commented on src/crypto/key.cpp
> +    }
要判断当前的内存类型，是否需要重新分配内存

2020-11-16 02:32 UTC, StoneJobs approved these changes

2020-11-16 06:59 UTC, cchanm approved these changes

2020-11-17 02:37 UTC, merged