Add Remove key RPC
BigBang-Foundation/BigBang pull request #50
Opened 2020-11-23 09:50 UTC by AlexiaChen

issue #37 

This version is simple and Remove Key advanced version will coming soon after one or two weeks.

2020-12-04 06:22 UTC, cchanm requested changes

2020-12-04 06:22 UTC, cchanm commented on script/template/rpc.json
> +        "example": [{
这里的格式与clang-format不一至，我电脑上修改一下，然后保存，则很多地方都修改了，都是这样的格式被修改了，看看能不能调整一下使用clang-format

2020-12-04 06:22 UTC, cchanm commented on src/bigbang/rpcmod.cpp
> +    if (address.IsTemplate())
建议增加支持模板地址的删除功能

2020-12-04 06:28 UTC, cchanm commented on src/bigbang/rpcmod.cpp
> +    if (spParam->fSynctx && !pService->ResynchronizeWalletTx())
ResynchronizeWalletTx这步比较耗时，建议不要重新同步钱包交易

2020-12-07 02:51 UTC, AlexiaChen commented on src/bigbang/rpcmod.cpp
> +    if (spParam->fSynctx && !pService->ResynchronizeWalletTx())
不是已经没有钱包交易了么？你的新PR，我要配合你的新PR来改吧？

2020-12-07 02:51 UTC, AlexiaChen commented on src/bigbang/rpcmod.cpp
> +    if (address.IsTemplate())
好的。

2020-12-07 02:52 UTC, AlexiaChen commented on script/template/rpc.json
> +        "example": [{
我试试

2020-12-07 03:55 UTC, AlexiaChen commented on src/bigbang/rpcmod.cpp
> +    if (address.IsTemplate())
这个功能与addnewtemplate保持一致，我觉得要重新实现各removetemplate的RPC来做，不然removekey容易引起误会。addkey  importkey与 removekey保持对应  importtemplate addnewtemplate与removetemplate保持对应

2020-12-07 03:55 UTC, AlexiaChen commented on script/template/rpc.json
> +        "example": [{
我试试

2020-12-07 03:57 UTC, AlexiaChen commented on src/bigbang/rpcmod.cpp
> +    if (spParam->fSynctx && !pService->ResynchronizeWalletTx())
这个重新同步的删除了。你看看

2020-12-08 08:42 UTC, merged

2020-12-08 08:47 UTC, AlexiaChen reviewed
good