Refactor Bigbang's hashing on arm64 platform
BigBang-Foundation/BigBang pull request #84
Opened 2021-01-15 06:35 UTC by ouyun

Refactor Bigbang's hashing on arm64 platform.

2021-01-25 06:17 UTC, AlexiaChen requested changes

2021-01-25 06:17 UTC, AlexiaChen commented on CMakeLists.txt
> +    # string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O0")
这里直接删除掉，就不用注释了。

2021-01-25 06:17 UTC, AlexiaChen commented on src/bigbang/core.cpp
> +//        DEBUG(ERR_BLOCK_PROOF_OF_WORK_INVALID, "monero hash error: proof[%s] vs. target[%s] with bits[%d]",
这里同上

2021-01-25 06:17 UTC, AlexiaChen commented on test/slowhash_tests.cpp
> +//#include "pow_hash/hash-ops.h"
这里同上

2021-01-25 06:17 UTC, AlexiaChen commented on test/slowhash_tests.cpp
> +// Copyright (c) 2019-2020 The Bigbang developers
这里是2019-2021，到时候你合并master就可以了

2021-01-26 02:06 UTC, shangqd approved these changes

2021-01-26 02:12 UTC, AlexiaChen approved these changes

2021-01-26 02:13 UTC, cchanm approved these changes

2021-01-26 02:14 UTC, merged